# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "firewire_ohci" "usb_storage" "sd_mod" "sr_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ]; # "wl"
  boot.extraModulePackages = [ ]; # config.boot.kernelPackages.broadcom_sta

  fileSystems."/" =
    { device = "/dev/disk/by-label/msdos";
      fsType = "ext4";
    };

 #  swapDevices = [
 #  {
 #    device = "~/.swapfile";
 #  }
 # ];


  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
